<?php
if (!defined('TYPO3_MODE')) {
	die ('Access denied.');
}
// check the p2c that have categories_id=$cat_source_id
$qry=$GLOBALS['TYPO3_DB']->SELECTquery('p2c.*', // SELECT ...
	'tx_multishop_products_to_categories p2c', // FROM ...
	'', // WHERE...
	'p2c.crumbar_identifier', // GROUP BY...
	'', // ORDER BY...
	'' // LIMIT ...
);
$categories_query=$GLOBALS['TYPO3_DB']->sql_query($qry);
while ($rs=$GLOBALS['TYPO3_DB']->sql_fetch_assoc($categories_query)) {

}
?>